name: PlatformIO CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install PlatformIO Core
        run: pip install -U platformio

      - name: Cache PlatformIO packages
        uses: actions/cache@v4
        with:
          path: ~/.platformio/packages
          key: ${{ runner.os }}-pio

      - name: Build project
        run: pio run

      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ github.sha }}
          path: .pio/build/adafruit_feather_esp32_v2/firmware.bin
